### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Tab0XTang** [robertzhangwenjie/gitbook2pdf#1]
<img width="361" alt="1670246213820" src="https://user-images.githubusercontent.com/96402640/205646517-8cf23774-c6dd-4114-b284-b876ad1af225.png">

**Comment by robertzhangwenjie** [comment]
看下你执行的命令

**Comment by Tab0XTang** [comment]
> 看下你执行的命令

docker run -it -v E/gitbook文章下载/output:/app/output zhangwenjie/gitbook2pdf https://www.xxxxrity.wiki/about/readme

**Comment by robertzhangwenjie** [comment]
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/35749198/205652047-a9609f37-c624-4d8a-9811-d5b19a11ac50.png">
我随便换了一个url，看起来是ok的

**Comment by Tab0XTang** [comment]
那我再试试吧谢谢

**Comment by Tab0XTang** [comment]
主机是win影响吗

**Comment by robertzhangwenjie** [comment]
> 主机是win影响吗

我制作的镜像支持linux/arm64和linux/amd64，windows 可能有问题，我可以再重新做一个支持windows的

**Comment by robertzhangwenjie** [comment]
我增加了几个平台的支持，你重新试下
<img width="732" alt="image" src="https://user-images.githubusercontent.com/35749198/205800612-16c18ec1-063e-4e5b-b692-7ccbcac6377d.png">

**Comment by Tab0XTang** [comment]
大佬，看一下，镜像重新拉取了还是报错，![image](https://user-images.githubusercontent.com/96402640/205875688-e0ad35eb-0979-413b-9ab7-0a0f258f17d3.png)

**Comment by weti96** [comment]
> 大佬，看一下，镜像重新拉取了还是报错，![image](https://user-images.githubusercontent.com/96402640/205875688-e0ad35eb-0979-413b-9ab7-0a0f258f17d3.png)

需要补充文件名，<you urls> <pdf name>

**Comment by robertzhangwenjie** [comment]
你用的是wsl吗？

**Comment by hanshou101** [comment]
![image](https://user-images.githubusercontent.com/19248935/221435478-b5a787af-e9db-4eda-ba6e-76466d60d349.png)
同样的问题

环境是【真机Win10】+  【WSL2 + Kali-Linux】。

指令是这条：```docker run -it -v `pwd`/output:/app/output zhangwenjie/gitbook2pdf https://my-hack-tricks.gitbook.io/my-hacktricks```

**Comment by hanshou101** [comment]
![image](https://user-images.githubusercontent.com/19248935/221435894-290582e1-f43f-481e-b6bc-123095fd0ddc.png)


git clone 源码后，仍然报这个问题

**Comment by hanshou101** [comment]
![image](https://user-images.githubusercontent.com/19248935/221436061-8ff8ad74-112f-4a5b-8e28-35c568a9404f.png)
![image](https://user-images.githubusercontent.com/19248935/221436086-e9768632-7f98-4c38-beb6-e561001f4b45.png)

需要传两个参数。

破案了。

**Comment by robertzhangwenjie** [comment]
> ![image](https://user-images.githubusercontent.com/19248935/221436061-8ff8ad74-112f-4a5b-8e28-35c568a9404f.png) ![image](https://user-images.githubusercontent.com/19248935/221436086-e9768632-7f98-4c38-beb6-e561001f4b45.png)
> 
> 需要传两个参数。
> 
> 破案了。

已补充 readme，感谢反馈！
